### ISSUE TITLE
Use IRC bouncer

### ISSUE THREAD

**Issue by bazz1tv** [bazzinotti/ayumi#65]
Although I recently added plugin management .. perhaps the best way to seamlessly update ayumi is through an IRC bouncer such as znc

**Comment by bazz1tv** [comment]
This is pretty much set, except it will need modifications when I learn to have ayumi function on different IRC servers :)

**Comment by rikai** [comment]
Heh, you and i are taking different approaches to this...

I've been considering taking the route of making use of hagabaka/Quassel-Ruby (or perhaps trying to rewrite it) to allow multiple bots to connect to a single quassel core each with their own unique sessions/channels (since i make use of multiple bots, [rikai/gitbot](http://www.github.com/rikai/gitbot), [rikai/showbot](http://www.github.com/rikai/showbot) and perhaps others later.)

Would also potentially allow for interesting things like responding to relevant commands were used even while a bot was offline for maintainence/reboots, essentially using the fact that quassel is a native, multi-user client to make things as transparent as possible to the bots.

Maybe a little crazy. ;)
